"""Standalone quasar spectral fitting with NumPy and SciPy."""

from importlib.metadata import PackageNotFoundError as _PackageNotFoundError, version as _version

try:
    __version__ = _version("qsospec")
except _PackageNotFoundError:  # source checkout without installation
    __version__ = "0.1.0"

from . import lines, recipes
from .lines import LineDefinition
from .complex_recipes import ComponentRecipe, ComplexRecipe
from .fitting.local import fit_line_complex, fit_local
from .workflows.batch import BatchResult, fit_batch, fit_object_to_store
from .config import (
    BalmerPseudoContinuumConfig,
    GalacticExtinctionConfig,
    GaussianComponent,
    GlobalContinuumConfig,
    HalphaComplexConfig,
    HbetaComplexConfig,
    IronTemplateConfig,
    LyaNVComplexConfig,
    LineComplexConfig,
    LocalFitConfig,
    LorentzianComponent,
    MgIIComplexConfig,
    PowerLawConfig,
    UncertaintyConfig,
)
from .extinction import (
    correct_spectrum,
    correct_spectrum_data,
    f99_dereddening_factor,
    galactic_dereddening_factor,
    prepare_spectrum,
    preflight_galactic_extinction,
    query_galactic_ebv,
    wang2019_extinction_mag,
)
from .fitting.global_fit import (
    fit_global_continuum,
    fit_global_hbeta,
    fit_global_lines,
    fit_halpha_complex,
    fit_hbeta_complex,
    fit_mgii_complex,
)
from .halpha_classification import (
    HalphaModelGridResult,
    HalphaModelSelectionConfig,
    LineSpreadFunctionConfig,
    diagnostic_bic_sweep,
    fit_halpha_model_grid,
    intrinsic_fwhm_kms,
    observed_fwhm_kms,
    observed_halpha_width_bounds,
)
from .hei_pgamma_classification import (
    HEI_PGAMMA_WINDOW,
    HeIPagammaModelPairResult,
    HeIPagammaModelSelectionConfig,
    fit_hei_pgamma_model_pair,
    hei_pgamma_classification_recipe,
)
from .broad_narrow_measurements import (
    COMPLEX_ORDER as BROAD_NARROW_COMPLEX_ORDER,
    MEASUREMENT_SCHEMA_VERSION as BROAD_NARROW_MEASUREMENT_SCHEMA_VERSION,
    BroadNarrowMeasurementConfig,
    broad_narrow_recipe,
    measure_broad_narrow_complex,
    measure_broad_narrow_complexes,
    measurement_record as broad_narrow_measurement_record,
    signed_to_uint64_string,
)
from .narrow_line_calibration import (
    selection_mask as narrow_line_calibration_selection_mask,
    stratified_recovery as narrow_line_stratified_recovery,
    summarize_recovery as summarize_narrow_line_recovery,
    threshold_sweep as narrow_line_calibration_threshold_sweep,
)
from .io.products import (
    GlobalQAPlotConfig,
    resolve_qa_plot_config,
    write_global_hbeta_products,
    write_global_line_products,
)
from .global_result import (
    EmissionComplexResult,
    GlobalContinuumResult,
    HbetaComplexResult,
    WorkflowResult,
)
from .workflows.host_workflow import (
    HostWorkflowResult,
    fit_global_hbeta_workflow,
    fit_global_lines_workflow,
    fit_with_optional_host_decomp,
)
from .workflows.host import (
    EuclidHostScaleConfig,
    EuclidHostScaleFit,
    euclid_nir_line_mask,
    fit_euclid_host_aperture_scale,
)
from .metadata import SpectrumMetadata, resolve_spectrum_metadata
from .io.qa import render_qa
from .io.readers import (
    SpectrumInput,
    detect_fits_reader,
    discover_fits_inputs,
    read_input_manifest,
    read_spectrum,
    scan_parquet_spectra,
)
from .plotting import plot_line_result, plot_local_result, save_local_window_plots
from .result import FitResult, LocalFitResult
from .io.run_store import (
    RunStore,
    build_science_catalog,
    compute_derived_quantities,
    finalize_run,
    load_model,
    load_model_by_key,
    open_run,
)
from .spectrum import Spectrum
from .signed_lines import (
    LocalLinePatternResult,
    SignedLineAmplitudeResult,
    SignedLineComponent,
    fit_local_line_pattern,
    measure_signed_line_amplitude,
    measure_signed_line_grid,
)
from .luminosity import (
    MonochromaticLuminosity,
    bolometric_luminosity,
    luminosity_distance,
    monochromatic_luminosity,
)
from .templates import (
    BalmerAnchorRatios,
    BalmerSeriesTemplate,
    IronTemplate,
    balmer_bound_free_shape,
    evaluate_balmer_pseudocontinuum,
    evaluate_balmer_pseudocontinuum_with_derivatives,
    list_balmer_templates,
    list_iron_templates,
    load_balmer_anchor_ratios,
    load_balmer_template,
    load_iron_template,
)
from .warnings import FitWarning

__all__ = [
    "BalmerPseudoContinuumConfig",
    "BalmerAnchorRatios",
    "BalmerSeriesTemplate",
    "BROAD_NARROW_COMPLEX_ORDER",
    "BROAD_NARROW_MEASUREMENT_SCHEMA_VERSION",
    "BatchResult",
    "BroadNarrowMeasurementConfig",
    "ComponentRecipe",
    "ComplexRecipe",
    "FitResult",
    "EmissionComplexResult",
    "EuclidHostScaleConfig",
    "EuclidHostScaleFit",
    "GaussianComponent",
    "GalacticExtinctionConfig",
    "GlobalContinuumConfig",
    "GlobalContinuumResult",
    "GlobalQAPlotConfig",
    "HalphaComplexConfig",
    "HalphaModelGridResult",
    "HalphaModelSelectionConfig",
    "HEI_PGAMMA_WINDOW",
    "HeIPagammaModelPairResult",
    "HeIPagammaModelSelectionConfig",
    "HbetaComplexConfig",
    "HbetaComplexResult",
    "IronTemplate",
    "IronTemplateConfig",
    "LineComplexConfig",
    "LineDefinition",
    "LineSpreadFunctionConfig",
    "LyaNVComplexConfig",
    "LocalFitConfig",
    "LocalFitResult",
    "LorentzianComponent",
    "MgIIComplexConfig",
    "MonochromaticLuminosity",
    "FitWarning",
    "HostWorkflowResult",
    "WorkflowResult",
    "PowerLawConfig",
    "RunStore",
    "Spectrum",
    "SignedLineAmplitudeResult",
    "SignedLineComponent",
    "LocalLinePatternResult",
    "SpectrumInput",
    "SpectrumMetadata",
    "UncertaintyConfig",
    "balmer_bound_free_shape",
    "build_science_catalog",
    "bolometric_luminosity",
    "compute_derived_quantities",
    "correct_spectrum",
    "correct_spectrum_data",
    "detect_fits_reader",
    "discover_fits_inputs",
    "finalize_run",
    "fit_batch",
    "fit_euclid_host_aperture_scale",
    "f99_dereddening_factor",
    "galactic_dereddening_factor",
    "fit_global_continuum",
    "fit_global_hbeta",
    "fit_global_hbeta_workflow",
    "fit_global_lines",
    "fit_global_lines_workflow",
    "fit_halpha_complex",
    "fit_halpha_model_grid",
    "fit_hei_pgamma_model_pair",
    "hei_pgamma_classification_recipe",
    "fit_hbeta_complex",
    "fit_mgii_complex",
    "fit_line_complex",
    "fit_local_line_pattern",
    "fit_local",
    "fit_object_to_store",
    "fit_with_optional_host_decomp",
    "evaluate_balmer_pseudocontinuum",
    "evaluate_balmer_pseudocontinuum_with_derivatives",
    "euclid_nir_line_mask",
    "list_balmer_templates",
    "list_iron_templates",
    "load_balmer_anchor_ratios",
    "lines",
    "load_balmer_template",
    "load_iron_template",
    "load_model",
    "load_model_by_key",
    "luminosity_distance",
    "intrinsic_fwhm_kms",
    "monochromatic_luminosity",
    "measure_signed_line_amplitude",
    "measure_signed_line_grid",
    "open_run",
    "observed_fwhm_kms",
    "observed_halpha_width_bounds",
    "narrow_line_calibration_selection_mask",
    "narrow_line_calibration_threshold_sweep",
    "narrow_line_stratified_recovery",
    "prepare_spectrum",
    "preflight_galactic_extinction",
    "query_galactic_ebv",
    "plot_line_result",
    "plot_local_result",
    "recipes",
    "read_input_manifest",
    "read_spectrum",
    "render_qa",
    "resolve_qa_plot_config",
    "resolve_spectrum_metadata",
    "summarize_narrow_line_recovery",
    "save_local_window_plots",
    "scan_parquet_spectra",
    "write_global_hbeta_products",
    "write_global_line_products",
    "wang2019_extinction_mag",
    "diagnostic_bic_sweep",
    "broad_narrow_recipe",
    "broad_narrow_measurement_record",
    "measure_broad_narrow_complex",
    "measure_broad_narrow_complexes",
    "signed_to_uint64_string",
]
